version: '3'
services:
  archie:
    build: .
    image: 'archie'
    labels:
      wizard: 'wizard'
    ports:
      - "3000:3000"
    networks:
      - archie_net
    tty: true

networks:
  archie_net:
    external:
      name: archie_net