version: '3'
services:
  postgres:
    image: 'younccat/wizard-primary-db:latest'
    labels: 
      wizard: 'wizard'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webnet
  
  redis:
    image: redis:latest
    labels:
      wizard: 'wizard'
    volumes:
      - redis_data:/var/lib/redis/data
    networks:
      - webnet

  nginx:
    image: nginx:latest
    labels: 
      wizard: 'wizard'
    volumes:
      - ./docker/configs/nginx.conf
    networks:
      - webnet
    
  archie:
    build: '.'
    labels: 
      wizard: 'wizard'
    ports: 
      - "3000:3000"
    depends_on:
      - postgres
      - nginx
      - redis
    networks:
      - webnet  

networks:
  ? webnet
    
volumes:
  postgres_data:
    external: true
  redis_data:
    external: true  